/* Generated By:JavaCC: Do not edit this line. YappParserConstants.java */
package com.github.kmizu.yapp.parser;

public interface YappParserConstants {

  int EOF = 0;
  int MULTI_LINE_COMMENT = 5;
  int LINE_COMMENT = 6;
  int GRAMMAR = 7;
  int FAIL = 8;
  int BOUNDED = 9;
  int MACRO = 10;
  int ANY = 11;
  int LARROW = 12;
  int EQUAL = 13;
  int AND = 14;
  int NOT = 15;
  int QUESTION = 16;
  int COLON = 17;
  int BAR = 18;
  int SLASH = 19;
  int STAR = 20;
  int PLUS = 21;
  int EMPTY = 22;
  int LPAREN = 23;
  int RPAREN = 24;
  int LBRACE = 25;
  int RBRACE = 26;
  int CUT = 27;
  int COMMA = 28;
  int SEMI_COLON = 29;
  int MACRO_PARAM = 30;
  int MACRO_NAME = 31;
  int ID = 32;
  int CHAR_CLASS = 33;
  int CODE = 34;
  int EXP_CODE = 35;
  int PREDICATE = 36;
  int STRING = 37;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<MULTI_LINE_COMMENT>",
    "<LINE_COMMENT>",
    "\"grammar\"",
    "\"fail\"",
    "\"bounded\"",
    "\"macro\"",
    "<ANY>",
    "\"<-\"",
    "\"=\"",
    "\"&\"",
    "\"!\"",
    "\"?\"",
    "\":\"",
    "\"|\"",
    "\"/\"",
    "\"*\"",
    "\"+\"",
    "\"()\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"^\"",
    "\",\"",
    "\";\"",
    "<MACRO_PARAM>",
    "<MACRO_NAME>",
    "<ID>",
    "<CHAR_CLASS>",
    "<CODE>",
    "<EXP_CODE>",
    "<PREDICATE>",
    "<STRING>",
  };

}
